services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: yourls
      MYSQL_DATABASE: yourls
      MYSQL_PASSWORD: very-secure-database-password
      MYSQL_ROOT_PASSWORD: very-secure-database-root-password
    volumes:
      - mysql-mysql:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
  yourls:
    image: yourls:latest
    environment:
      YOURLS_PASS: very-secury-admin-password
      YOURLS_SITE: https://myyourls.example.com
      YOURLS_USER: yourls-admin
      YOURLS_DB_HOST: mysql
      YOURLS_DB_NAME: yourls
      YOURLS_DB_PASS: very-secure-database-password
      YOURLS_DB_USER: yourls
    ports:
      - 80
    volumes:
      - security-conf:/etc/apache2/conf-enabled/security.conf:ro
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  mysql-mysql:
    driver_opts:
      size: 2Gi
  security-conf:
    driver_opts:
      size: 2Gi
