services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.126.0
    environment:
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
      PASSWORD: ${CODESERVER_PASSWORD}
      SUDO_PASSWORD: ${CODESERVER_SUDO_PASSWORD}
      DEFAULT_WORKSPACE: /config/workspace
    ports:
      - 8443
    volumes:
      - config:/config
      - projects:/projects
      - runtipi:/runtipi
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  config:
    driver_opts:
      size: 2Gi
  runtipi:
    driver_opts:
      size: 2Gi
  projects:
    driver_opts:
      size: 2Gi
