services:
  joplin:
    image: joplin/server:3.7.1
    environment:
      APP_PORT: "22300"
      DB_CLIENT: pg
      APP_BASE_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}/
      POSTGRES_HOST: db-joplin
      POSTGRES_PORT: "5432"
      POSTGRES_USER: tipi
      MAX_TIME_DRIFT: "0"
      POSTGRES_DATABASE: joplin
      POSTGRES_PASSWORD: ${JOPLIN_DB_PASSWORD}
    ports:
      - 22300
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  db-joplin:
    image: postgres:14.2
    environment:
      POSTGRES_DB: joplin
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: ${JOPLIN_DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  postgres:
    driver_opts:
      size: 2Gi
