services:
  owncast:
    image: owncast/owncast:0.2.5
    ports:
      - 8080
      - 1935
    volumes:
      - data:/app/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 2Gi
