services:
  baikal:
    image: ghcr.io/aalmenar/baikal:0.11.1
    ports:
      - 80
    volumes:
      - config:/var/www/baikal/config
      - specific:/var/www/baikal/Specific
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  config:
    driver_opts:
      size: 2Gi
  specific:
    driver_opts:
      size: 2Gi
