services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:1.11.2
    environment:
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
      RATE_LIMIT: false]
      WS_FALLBACK: "false"
    ports:
      - 3000
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
