services:
  vaultwarden:
    image: vaultwarden/server:1.36.0
    environment:
      DOMAIN: ${PUBLIC_URL}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
    ports:
      - 80
    volumes:
      - data:/data
    deploy:
      resources:
        reservations:
          cpus: 0.1
          memory: 128M
volumes:
  data:
    driver_opts:
      size: 2Gi
