services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    environment:
      DISABLE_IPV6: "true"
    ports:
      - 8080
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
