services:
  jellyfin-vue:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable.2024-10-14.a47a7d5
    ports:
      - 80
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
