services:
  n8n-2:
    image: n8nio/n8n:2.29.3
    environment:
      DB_TYPE: postgresdb
      WEBHOOK_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}
      N8N_SECURE_COOKIE: "false"
      DB_POSTGRESDB_HOST: n8n-db
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_USER: n8n
      N8N_EDITOR_BASE_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_PASSWORD: ${N8N_NR_DB_PASSWORD}
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
    ports:
      - 5678
    volumes:
      - n8n:/home/node/.n8n
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  n8n-db:
    image: postgres:18
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
      POSTGRES_NON_ROOT_USER: n8n
      POSTGRES_NON_ROOT_PASSWORD: ${N8N_NR_DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql
      - init-data-sh:/docker-entrypoint-initdb.d/init-data.sh
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
  n8n-init:
    image: bash:5.3.15
    command:
      - sh
      - -c
      - chown -R 1000:1000 /home/node/.n8n
    volumes:
      - n8n:/home/node/.n8n
    deploy:
      resources:
        reservations:
          cpus: 0.1
          memory: 256M
volumes:
  n8n:
    driver_opts:
      size: 2Gi
  postgres:
    driver_opts:
      size: 2Gi
  init-data-sh:
    driver_opts:
      size: 2Gi
