services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
      VERSION: ${MC_VERSION}
    ports:
      - 25565
    volumes:
      - minecraft-data:/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  minecraft-data:
    driver_opts:
      size: 2Gi
