services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  database:
    driver_opts:
      size: 2Gi
