services:
  dns-server:
    image: technitium/dns-server:latest
    environment:
      DNS_SERVER_DOMAIN: technitium.example.com
    ports:
      - 5380
      - 53/udp
    volumes:
      - config:/etc/dns/config
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  config:
    driver_opts:
      size: 2Gi
