services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_USER: chevereto
      MYSQL_DATABASE: chevereto
      MYSQL_PASSWORD: chevereto
      MARIADB_ROOT_PASSWORD: chevereto
    volumes:
      - chevereto-mariadb:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
  chevereto:
    image: ghcr.io/chevereto/chevereto:4.4
    environment:
      CHEVERETO_DB_HOST: mariadb
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PASS: chevereto
      CHEVERETO_DB_PORT: "3306"
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_ASSET_STORAGE_URL: /images/_assets
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/images/_assets
    ports:
      - 80
    volumes:
      - chevereto:/var/www/html/images
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  chevereto:
    driver_opts:
      size: 2Gi
  chevereto-mariadb:
    driver_opts:
      size: 2Gi
