services:
  radarr:
    image: ghcr.io/linuxserver/radarr:6.2.1
    environment:
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
    ports:
      - 7878
    volumes:
      - data:/config
      - media:/media
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 2Gi
  media:
    driver_opts:
      size: 2Gi
