services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    environment:
      "[object Object]": ""
    ports:
      - 3000
    volumes:
      - data:/app/config
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 2Gi
