services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:latest
    environment:
      GRAMPSWEB_TREE: Gramps Web
    ports:
      - 5000
    volumes:
      - users:/app/users
      - indexdir:/app/indexdir
      - thumbnail-cache:/app/thumbnail_cache
      - cache:/app/cache
      - secret:/app/secret
      - database:/root/.gramps/grampsdb
      - media:/app/media
      - tmp:/tmp
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  tmp:
    driver_opts:
      size: 2Gi
  cache:
    driver_opts:
      size: 2Gi
  media:
    driver_opts:
      size: 2Gi
  users:
    driver_opts:
      size: 2Gi
  secret:
    driver_opts:
      size: 2Gi
  database:
    driver_opts:
      size: 2Gi
  indexdir:
    driver_opts:
      size: 2Gi
  thumbnail-cache:
    driver_opts:
      size: 2Gi
