services:
  mongodb:
    image: mongo:8.0.26
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    ports:
      - 27017
    volumes:
      - data:/data/db
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  data:
    driver_opts:
      size: 2Gi
