services:
  nodered:
    image: nodered/node-red:5.0.1
    ports:
      - 1880
    volumes:
      - data:/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 2Gi
