services:
  umami-analytics:
    image: ghcr.io/umami-software/umami:3.2.0
    environment:
      APP_SECRET: ${UMAMI_ANALYTICS_APP_SECRET}
      DATABASE_URL: postgresql://umami:${UMAMI_ANALYTICS_DB_PASSWORD}@umami-analytics-db:5432/umami-analytics-db
      DATABASE_TYPE: postgresql
    ports:
      - 3000
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  umami-analytics-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami-analytics-db
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: ${UMAMI_ANALYTICS_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  db:
    driver_opts:
      size: 2Gi
