services:
  homeassistant-1:
    image: ghcr.io/home-assistant/home-assistant:2026.7.1
    environment:
      TZ: ${TZ}
    ports:
      - 8123
    volumes:
      - config:/config
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  config:
    driver_opts:
      size: 2Gi
