services:
  logto:
    image: svhd/logto:1.41.0
    entrypoint:
      - sh
      - -c
      - npm run cli db seed -- --swe && npm start
    environment:
      DB_URL: postgres://tipi:${LOGTO_DB_PASSWORD}@logto-db:5432/logto
      ENDPOINT: https://${PUBLIC_HOST}
      NODE_ENV: production
      ADMIN_ENDPOINT: https://${LOGTO_ADMIN_URL}
      TRUST_PROXY_HEADER: "1"
    ports:
      - 3001
      - 3002
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  logto-db:
    image: postgres:14
    environment:
      POSTGRES_DB: logto
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: ${LOGTO_DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  postgres:
    driver_opts:
      size: 2Gi
