services:
  mealie-1:
    image: ghcr.io/mealie-recipes/mealie:v3.20.1
    environment:
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
      BASE_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}
      MAX_WORKERS: "1"
      ALLOW_SIGNUP: ${MEALIE_ALLOW_SIGNUP}
      WEB_CONCURRENCY: "1"
    ports:
      - 9000
    volumes:
      - data:/app/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 2Gi
