services:
  db:
    image: mariadb:lts
    environment:
      MYSQL_USER: firefly
      MYSQL_DATABASE: firefly
      MYSQL_PASSWORD: MySecretDatabasePassword
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
  app:
    image: fireflyiii/core:latest
    ports:
      - 8080
    volumes:
      - upload:/var/www/html/storage/upload
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  mysql:
    driver_opts:
      size: 2Gi
  upload:
    driver_opts:
      size: 2Gi
