services:
  grav:
    image: lscr.io/linuxserver/grav:1.8.0
    environment:
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
    ports:
      - 80
    volumes:
      - grav-comfig:/config
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  grav-comfig:
    driver_opts:
      size: 2Gi
