services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    environment:
      TZ: Europe/Berlin
      PGID: "1000"
      PUID: "1000"
    ports:
      - 3000
    volumes:
      - config:/config
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  config:
    driver_opts:
      size: 2Gi
