services:
  peppermint:
    image: pepperlabs/peppermint:latest
    environment:
      API_URL: "{APP_PROTOCOL:-http}://${PEPPERMINT_DOMAIN_API}"
      DB_HOST: peppermint-db
      DB_PASSWORD: ${PEPPERMINT_DB_PASSWORD}
      DB_USERNAME: tipi
    ports:
      - 3000
      - 5003
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  peppermint-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: peppermint
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: ${PEPPERMINT_DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  postgres:
    driver_opts:
      size: 2Gi
