services:
  jira:
    image: atlassian/jira-core:9.9.2
    environment:
      VERBOSE_LOGS: "false"
      ATL_PROXY_NAME: jira.example.com
      ATL_PROXY_PORT: "443"
      ATL_TOMCAT_PORT: "8090"
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: "false"
      JVM_MAXIMUM_MEMORY: 1024m
      JVM_MINIMUM_MEMORY: 1024m
      ATL_AUTOLOGIN_COOKIE_AGE: "1209600"
      ATL_TOMCAT_TRUSTEDPROXIES: 192.168.0.0/24|10.0.0.0/8|172.16.0.0/16
      JVM_RESERVED_CODE_CACHE_SIZE: 256m
      ATL_TOMCAT_ACCESS_LOGS_MAXDAYS: "360"
    ports:
      - 8080
    volumes:
      - data:/var/atlassian/application-data/jira
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  confluence:
    image: atlassian/confluence:9.0.3
    environment:
      VERBOSE_LOGS: "false"
      ATL_PROXY_NAME: confluence.example.com
      ATL_PROXY_PORT: "443"
      ATL_TOMCAT_PORT: "8090"
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: "false"
      JVM_MAXIMUM_MEMORY: 1024m
      JVM_MINIMUM_MEMORY: 1024m
      ATL_AUTOLOGIN_COOKIE_AGE: "1209600"
      ATL_TOMCAT_TRUSTEDPROXIES: 192.168.0.0/24|10.0.0.0/8|172.16.0.0/16
      JVM_RESERVED_CODE_CACHE_SIZE: 256m
      ATL_TOMCAT_ACCESS_LOGS_MAXDAYS: "360"
    expose:
      - 8090
    volumes:
      - data:/var/atlassian/application-data/confluence
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  postgresql:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - psql:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  data:
    driver_opts:
      size: 2Gi
  psql:
    driver_opts:
      size: 2Gi
