services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:v0.7.1-ls84
    environment:
      TZ: ${TZ}
      PGID: "1000"
      PUID: "1000"
    ports:
      - 8090
    volumes:
      - mylar3-config:/config
      - comics:/comics
      - mylar3-downloads:/downloads
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  comics:
    driver_opts:
      size: 2Gi
  mylar3-config:
    driver_opts:
      size: 2Gi
  mylar3-downloads:
    driver_opts:
      size: 2Gi
