services:
  db:
    image: postgres:18.4
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: mattermost
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  mattermost:
    image: mattermost/mattermost-team-edition:11.7.6
    environment:
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:${DB_PASSWORD}@${POSTGRES_HOST}:5432/mattermost?sslmode=disable&connect_timeout=10
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SERVICESETTINGS_SITEURL: ${PUBLIC_URL}
    ports:
      - 8065
    volumes:
      - data:/mattermost/data
      - config:/mattermost/config
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 512M
volumes:
  db:
    driver_opts:
      size: 5Gi
  data:
    driver_opts:
      size: 10Gi
  config:
    driver_opts:
      size: 1Gi
