services:
  plausible-ce:
    image: ghcr.io/plausible/community-edition:v2.1.5
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    environment:
      BASE_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}
      MAILER_NAME: ${PLAUSIBLE_MAILER_NAME}
      DATABASE_URL: postgres://tipi:${PLAUSIBLE_DB_PASSWORD}@plausible-db:5432/plausible-db
      MAILER_EMAIL: ${PLAUSIBLE_MAILER_EMAIL}}
      SMTP_RETRIES: ${PLAUSIBLE_SMTP_RETRIES}
      SMTP_USER_PWD: ${PLAUSIBLE_SMTP_USER_PWD}
      MAILER_ADAPTER: ${PLAUSIBLE_MAILER_ADAPTER}
      MAILGUN_DOMAIN: ${PLAUSIBLE_MAILGUN_DOMAIN}
      SMTP_HOST_ADDR: ${PLAUSIBLE_SMTP_HOST_ADDR}
      SMTP_HOST_PORT: ${PLAUSIBLE_SMTP_HOST_PORT}
      SMTP_USER_NAME: ${PLAUSIBLE_SMTP_USER_NAME}
      TOTP_VAULT_KEY: ${PLAUSIBLE_TOTP_VAULT_KEY}
      MAILGUN_API_KEY: ${PLAUSIBLE_MAILGUN_API_KEY}
      MAXMIND_EDITION: ${PLAUSIBLE_MAXMIND_EDITION}
      SECRET_KEY_BASE: ${PLAUSIBLE_SECRET_KEY_BASE}
      GOOGLE_CLIENT_ID: ${PLAUSIBLE_GOOGLE_CLIENT_ID}
      MAILGUN_BASE_URI: ${PLAUSIBLE_MAILGUN_BASE_URI}
      MANDRILL_API_KEY: ${PLAUSIBLE_MANDRILL_API_KEY}
      POSTMARK_API_KEY: ${PLAUSIBLE_POSTMARK_API_KEY}
      SENDGRID_API_KEY: ${PLAUSIBLE_SENDGRID_API_KEY}
      MAXMIND_LICENSE_KEY: ${PLAUSIBLE_MAXMIND_LICENSE_KEY}
      DISABLE_REGISTRATION: ${PLAUSIBLE_DISABLE_REGISTRATION}
      GOOGLE_CLIENT_SECRET: ${PLAUSIBLE_GOOGLE_CLIENT_SECRET}
      SMTP_HOST_SSL_ENABLED: ${PLAUSIBLE_SMTP_HOST_SSL_ENABLED}
      CLICKHOUSE_DATABASE_URL: http://plausible-events-db:8123/plausible_events_db
      ENABLE_EMAIL_VERIFICATION: ${PLAUSIBLE_ENABLE_EMAIL_VERIFICATION}
    ports:
      - 8000
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  plausible-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: plausible-db
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: ${PLAUSIBLE_DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
  plausible-events-db:
    image: clickhouse/clickhouse-server:26.6.1.1193
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - clickhouse-config-xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - clickhouse-user-config-xml:/etc/clickhouse-server/users.d/logging.xml:ro
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  database:
    driver_opts:
      size: 2Gi
  event-data:
    driver_opts:
      size: 2Gi
  event-logs:
    driver_opts:
      size: 2Gi
  clickhouse-config-xml:
    driver_opts:
      size: 2Gi
  clickhouse-user-config-xml:
    driver_opts:
      size: 2Gi
