services:
  photoprism:
    image: photoprism/photoprism:latest
    environment:
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_SITE_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}/
      PHOTOPRISM_LOG_LEVEL: info
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_JPEG_QUALITY: "85"
      PHOTOPRISM_SITE_CAPTION: AI-Powered Photos App
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: photoprism-db:3306
      PHOTOPRISM_ORIGINALS_LIMIT: "5000"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_HTTP_COMPRESSION: gzip
      PHOTOPRISM_DATABASE_PASSWORD: ${DB_PASSWORD}
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
    ports:
      - 2342
    volumes:
      - images:/photoprism/originals
      - storage:/photoprism/storage
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  photoprism-db:
    image: mariadb:10.8
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    environment:
      MARIADB_USER: photoprism
      MARIADB_DATABASE: photoprism
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  images:
    driver_opts:
      size: 2Gi
  mariadb:
    driver_opts:
      size: 2Gi
  storage:
    driver_opts:
      size: 2Gi
