services:
  searxng:
    image: searxng/searxng:latest
    environment:
      BASE_URL: ${APP_PROTOCOL}://${PUBLIC_HOST}/
      BIND_ADDRESS: 0.0.0.0:8080
      SEARXNG_SECRET: ${SEARXNG_SECRET_KEY}
    ports:
      - 8080
    volumes:
      - data:/etc/searxng
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  data:
    driver_opts:
      size: 2Gi
