services:
  mongo:
    image: mongo:7.0.37
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    ports:
      - 27017
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
