services:
  openclaw:
    image: alpine/openclaw:latest
    environment:
      NODE_ENV: production
      OLLAMA_HOST: ${OLLAMA_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
    ports:
      - 18789
    volumes:
      - config:/home/node/.openclaw
      - workspace:/home/node/.openclaw/workspace
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
volumes:
  config:
    driver_opts:
      size: 2Gi
  workspace:
    driver_opts:
      size: 2Gi
