services:
  semaphore:
    image: semaphoreui/semaphore:v2.18.14
    environment:
      TZ: ${TZ}
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_DB_HOST: semaphore-db
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASSWORD}
      SEMAPHORE_DB_PORT: "5432"
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_LDAP_ACTIVATED: no
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
    ports:
      - 3000
    volumes:
      - repositories:/repositories
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 256M
  semaphore-db:
    image: postgres:14
    environment:
      POSTGRES_DB: semaphore
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: ${SEMAPHORE_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: 0.25
          memory: 512M
volumes:
  db:
    driver_opts:
      size: 2Gi
  repositories:
    driver_opts:
      size: 2Gi
